# -*- coding: utf-8 -*-
"""advance_sentiment_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QIs08-_3u5EjmJ_FATazC_SpG_uuTbkB

### How Transformers Work in Sentiment Analysis
A Transformer performs sentiment analysis by first converting a sentence into token embeddings and then applying self-attention to understand how each word relates to every other word in the sentence. This helps the model capture context effectively—for example, recognizing that “not” changes the meaning of “good” in “not good.”

In encoder-based models like BERT or RoBERTa, the sentence is processed bidirectionally, meaning the model looks at both left and right context simultaneously. The final sentence representation (usually from a special classification token) is passed through a neural classification layer that predicts whether the sentiment is positive, negative, or neutral

## Text --> Tokenization --> Embedding --> Self-Attention Layers --> Classification Head --> Sentiment
"""

!pip install -q transformers datasets evaluate accelerate

import numpy as np
import torch
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer, DataCollatorWithPadding, EarlyStoppingCallback
import evaluate
from sklearn.utils.class_weight import compute_class_weight

dataset = load_dataset('imdb')

dataset['train'] = dataset['train'].shuffle(seed=42).select(range(10000))
dataset['test'] = dataset['test'].shuffle(seed=42).select(range(5000))

model_name = "roberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize_function(examples):
   return tokenizer(
       examples['text'],
       truncation=True,
       max_length=256
   )


dataset = dataset.map(tokenize_function, batched=True)

dataset = dataset.remove_columns(['text'])
dataset = dataset.rename_column("label", 'labels')
dataset.set_format('torch')

labels = dataset["train"]["labels"]

# Convert to numpy array
labels = np.array(labels)

class_weights = compute_class_weight(
    class_weight="balanced",
    classes=np.unique(labels),
    y=labels
)

class_weights = torch.tensor(class_weights, dtype=torch.float)

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=2
)

from torch.nn import CrossEntropyLoss

class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.get("labels")
        outputs = model(**inputs)
        logits = outputs.get("logits")

        loss_fct = CrossEntropyLoss(weight=class_weights.to(model.device))
        loss = loss_fct(logits, labels)

        return (loss, outputs) if return_outputs else loss

accuracy = evaluate.load('accuracy')
f1 = evaluate.load('f1')


def compute_metrics(eval_pred):
   logits, labels = eval_pred
   predictions = np.argmax(logits, axis=1)

   acc = accuracy.compute(predictions=predictions, references=labels)
   f1_score = f1.compute(predictions=predictions, references=labels)


   return {
       'accuracy': acc['accuracy'],
       'f1': f1_score['f1']
   }

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    fp16=torch.cuda.is_available(),
    logging_dir="./logs",
    logging_steps=100
)

data_collator = DataCollatorWithPadding(tokenizer)

trainer = WeightedTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=2)]
)

trainer.train()

trainer.evaluate()

import torch
from torch.nn.functional import softmax

def predict(text):
    # Tokenize the input text
    inputs = tokenizer(text, return_tensors='pt', truncation=True, padding=True, max_length=128)
    inputs = {k: v.to(model.device) for k, v in inputs.items()}  # move to device (CPU/GPU)

    # Get model outputs
    with torch.no_grad():
        outputs = model(**inputs)  # pass inputs to model
        logits = outputs.logits    # raw predictions

    # Convert logits to probabilities
    probs = softmax(logits, dim=1)  # probability for each class

    # Get predicted class (0=ham, 1=spam)
    pred_class = torch.argmax(probs, dim=1).item()

    return pred_class, probs[0][pred_class].item()

text = "Congratulations! You won a free ticket."
label, confidence = predict(text)

print("Predicted label:", "spam" if label==1 else "ham")
print("Confidence:", confidence)